# Generated by Django 3.1.5 on 2024-09-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cat', models.CharField(max_length=100)),
                ('desc_cat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nif', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('data_registo', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_colaborador', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('passwd', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_forn', models.CharField(max_length=255)),
                ('email_form', models.EmailField(max_length=255, unique=True)),
                ('telefone_forn', models.CharField(blank=True, max_length=20, null=True)),
                ('nifc_forn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('foto_produto', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('sn_produto', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.categoria')),
                ('id_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='produto_stock', serialize=False, to='store.produtos')),
                ('quantidade_disponivel', models.IntegerField()),
                ('quantidade_reservada', models.IntegerField(blank=True, null=True)),
                ('data_ultima_atualizacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id_promocao', models.AutoField(primary_key=True, serialize=False)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inicio_desc', models.DateField()),
                ('fim_desc', models.DateField()),
                ('produtos', models.ManyToManyField(blank=True, related_name='promocoes', to='store.Produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_pedido', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido_json_form', models.JSONField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.clientes')),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('estado_pagamento', models.CharField(max_length=50)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasForn',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('compra_json_form', models.JSONField(blank=True, null=True)),
                ('valor_total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('estado_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('id_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fornecedores')),
            ],
        ),
    ]
