
ALTER TABLE HR.User_address DROP CONSTRAINT fk_user_address_userid;
ALTER TABLE HR.User_payment DROP CONSTRAINT fk_user_payment_userid;
ALTER TABLE HR.User_payment DROP CONSTRAINT fk_user_payment_addressid;
ALTER TABLE STATIC_CONTENT.Sub_Categories DROP CONSTRAINT fk_subcategories_categoryid;
ALTER TABLE DYNAMIC_CONTENT.Products DROP CONSTRAINT fk_products_categoryid;
ALTER TABLE DYNAMIC_CONTENT.Products DROP CONSTRAINT fk_products_brandid;
ALTER TABLE DYNAMIC_CONTENT.Stock DROP CONSTRAINT fk_stock_productid;
ALTER TABLE TRANSACTIONS.Orders DROP CONSTRAINT fk_orders_userid;
ALTER TABLE TRANSACTIONS.Payments DROP CONSTRAINT fk_payments_orderid;
ALTER TABLE TRANSACTIONS.Payments DROP CONSTRAINT fk_payments_userid;
ALTER TABLE PROMOS.Promotions DROP CONSTRAINT fk_promos_productid;
ALTER TABLE PROMOS.Promotions DROP CONSTRAINT fk_promos_categoryid;


TRUNCATE TABLE PROMOS.Promotions RESTART IDENTITY CASCADE;
TRUNCATE TABLE TRANSACTIONS.Payments RESTART IDENTITY CASCADE;
TRUNCATE TABLE TRANSACTIONS.Orders RESTART IDENTITY CASCADE;
TRUNCATE TABLE DYNAMIC_CONTENT.Stock RESTART IDENTITY CASCADE;
TRUNCATE TABLE DYNAMIC_CONTENT.Products RESTART IDENTITY CASCADE;
TRUNCATE TABLE DYNAMIC_CONTENT.Brands RESTART IDENTITY CASCADE;
TRUNCATE TABLE STATIC_CONTENT.Sub_Categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE STATIC_CONTENT.Categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE HR.User_payment RESTART IDENTITY CASCADE;
TRUNCATE TABLE HR.User_address RESTART IDENTITY CASCADE;
TRUNCATE TABLE HR.Users RESTART IDENTITY CASCADE;


ALTER TABLE HR.User_address ADD CONSTRAINT fk_user_address_userid FOREIGN KEY (UserID) REFERENCES HR.Users(UserID) ON DELETE CASCADE;
ALTER TABLE HR.User_payment ADD CONSTRAINT fk_user_payment_userid FOREIGN KEY (UserID) REFERENCES HR.Users(UserID) ON DELETE CASCADE;
ALTER TABLE HR.User_payment ADD CONSTRAINT fk_user_payment_addressid FOREIGN KEY (Billing_AddressID) REFERENCES HR.User_address(AddressID) ON DELETE SET NULL;
ALTER TABLE STATIC_CONTENT.Sub_Categories ADD CONSTRAINT fk_subcategories_categoryid FOREIGN KEY (CategoryID) REFERENCES STATIC_CONTENT.Categories(CategoryID) ON DELETE CASCADE;
ALTER TABLE DYNAMIC_CONTENT.Products ADD CONSTRAINT fk_products_categoryid FOREIGN KEY (CategoryID) REFERENCES STATIC_CONTENT.Categories(CategoryID) ON DELETE SET NULL;
ALTER TABLE DYNAMIC_CONTENT.Products ADD CONSTRAINT fk_products_brandid FOREIGN KEY (BrandID) REFERENCES DYNAMIC_CONTENT.Brands(BrandID) ON DELETE SET NULL;
ALTER TABLE DYNAMIC_CONTENT.Stock ADD CONSTRAINT fk_stock_productid FOREIGN KEY (ProductID) REFERENCES DYNAMIC_CONTENT.Products(ProductID) ON DELETE CASCADE;
ALTER TABLE TRANSACTIONS.Orders ADD CONSTRAINT fk_orders_userid FOREIGN KEY (UserID) REFERENCES HR.Users(UserID) ON DELETE CASCADE;
ALTER TABLE TRANSACTIONS.Payments ADD CONSTRAINT fk_payments_orderid FOREIGN KEY (OrderID) REFERENCES TRANSACTIONS.Orders(OrderID) ON DELETE CASCADE;
ALTER TABLE TRANSACTIONS.Payments ADD CONSTRAINT fk_payments_userid FOREIGN KEY (UserID) REFERENCES HR.Users(UserID) ON DELETE CASCADE;
ALTER TABLE PROMOS.Promotions ADD CONSTRAINT fk_promos_productid FOREIGN KEY (ProductID) REFERENCES DYNAMIC_CONTENT.Products(ProductID) ON DELETE SET NULL;
ALTER TABLE PROMOS.Promotions ADD CONSTRAINT fk_promos_categoryid FOREIGN KEY (CategoryID) REFERENCES STATIC_CONTENT.Categories(CategoryID) ON DELETE SET NULL;
